package ventanas;

import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import motor.Conexion;
import motor.Configuracion;
import motor.CopiaSeguridad;
import motor.Main;
import org.apache.log4j.Logger;

/**
 *
 * @author jmbalbas
 */
public class ConfigurarAplicacion extends javax.swing.JDialog {
    private String usuario;
    private Logger log;
    
    /**
     * Creates new form ConfigurarAplicacion
     */
    public ConfigurarAplicacion(java.awt.Frame parent, String usuario, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Configuracion");
        this.setLocationRelativeTo(null);
        
        // Iniciamos el log, si tenemos activo el debug
        if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) {
            Main iniciarlog = new Main();
            log = iniciarlog.getLog();
        }
        
        this.usuario = usuario;
        
        // Inicializamos los campos de pantalla
        if(Configuracion.getInstance().getProperty(Configuracion.AUTO_BACKUP).equals("si")) jCheckBoxCopiaAutomatica.setSelected(true);
        jLabelFechaUltimaCopia.setText(Configuracion.getInstance().getProperty(Configuracion.LAST_DATE_BACKUP));
        jTextFieldCarpetaTemporales.setText(Configuracion.getInstance().getProperty(Configuracion.TEMP_FOLDER));
        jTextFieldCarpetaPdfs.setText(Configuracion.getInstance().getProperty(Configuracion.PDF_FOLDER));
        jTextFieldCarpetaCopias.setText(Configuracion.getInstance().getProperty(Configuracion.BACKUP_FOLDER));
        jTextFieldCarpetaReportes.setText(Configuracion.getInstance().getProperty(Configuracion.REPORTS_FOLDER));
        jTextFieldNombreReporte.setText(Configuracion.getInstance().getProperty(Configuracion.REPORT_NAME));
        if(Configuracion.getInstance().getProperty(Configuracion.MULTIPLE_SESSION).equals("si")) jCheckBoxPermitirInicioSesionMultiple.setSelected(true);
        if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) jCheckBoxActivarDebug.setSelected(true);
        
        // Ruta relativa
        jLabelRutaRelativa1.setText(System.getProperty("user.dir") + File.separator);
        jLabelRutaRelativa2.setText(System.getProperty("user.dir") + File.separator);
        jLabelRutaRelativa3.setText(System.getProperty("user.dir") + File.separator);
        jLabelRutaRelativa4.setText(System.getProperty("user.dir") + File.separator);
        jLabelRutaRelativa5.setText(System.getProperty("user.dir") + File.separator);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCopiaAutomatica = new javax.swing.JCheckBox();
        jButtonRestaurarUltimaCopia = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelFechaUltimaCopia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldActual = new javax.swing.JPasswordField();
        jPasswordFieldNueva = new javax.swing.JPasswordField();
        jPasswordFieldRepetir = new javax.swing.JPasswordField();
        jButtonCambiarContraseña = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxActivarDebug = new javax.swing.JCheckBox();
        jCheckBoxPermitirInicioSesionMultiple = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCarpetaTemporales = new javax.swing.JTextField();
        jTextFieldCarpetaPdfs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCarpetaCopias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCarpetaReportes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNombreReporte = new javax.swing.JTextField();
        jLabelRutaRelativa1 = new javax.swing.JLabel();
        jLabelRutaRelativa2 = new javax.swing.JLabel();
        jLabelRutaRelativa3 = new javax.swing.JLabel();
        jLabelRutaRelativa4 = new javax.swing.JLabel();
        jLabelRutaRelativa5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGrabar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Copias de Seguridad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBoxCopiaAutomatica.setText("Copia de Seguridad automática");

        jButtonRestaurarUltimaCopia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/data_replace.png"))); // NOI18N
        jButtonRestaurarUltimaCopia.setText("Restaurar última copia realizada");
        jButtonRestaurarUltimaCopia.setToolTipText("Restaurar la última copia de seguridad realizada");
        jButtonRestaurarUltimaCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarUltimaCopiaActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha última Copia de Seguridad:");

        jLabelFechaUltimaCopia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFechaUltimaCopia.setForeground(new java.awt.Color(0, 51, 204));
        jLabelFechaUltimaCopia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaUltimaCopia.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRestaurarUltimaCopia, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBoxCopiaAutomatica)
                    .addComponent(jLabelFechaUltimaCopia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxCopiaAutomatica)
                .addGap(18, 18, 18)
                .addComponent(jButtonRestaurarUltimaCopia)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaUltimaCopia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Actual:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nueva:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Repetir:");

        jButtonCambiarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/replace2.png"))); // NOI18N
        jButtonCambiarContraseña.setText("Cambiar");
        jButtonCambiarContraseña.setToolTipText("Cambiar contraseña");
        jButtonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldActual, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldNueva)
                    .addComponent(jPasswordFieldRepetir))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordFieldActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCambiarContraseña)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jCheckBoxActivarDebug.setText("Activar debug");

        jCheckBoxPermitirInicioSesionMultiple.setText("Permitir inicio de sesión múltiple");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Carpeta temporal:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Carpeta pdfs:");

        jTextFieldCarpetaTemporales.setEditable(false);

        jTextFieldCarpetaPdfs.setEditable(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Carpeta copias:");

        jTextFieldCarpetaCopias.setEditable(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Carpeta reportes:");

        jTextFieldCarpetaReportes.setEditable(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre reporte:");

        jTextFieldNombreReporte.setEditable(false);

        jLabelRutaRelativa1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRutaRelativa1.setForeground(new java.awt.Color(0, 51, 204));
        jLabelRutaRelativa1.setText("jLabel9");

        jLabelRutaRelativa2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRutaRelativa2.setForeground(new java.awt.Color(0, 51, 204));
        jLabelRutaRelativa2.setText("jLabel9");

        jLabelRutaRelativa3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRutaRelativa3.setForeground(new java.awt.Color(0, 51, 204));
        jLabelRutaRelativa3.setText("jLabel9");

        jLabelRutaRelativa4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRutaRelativa4.setForeground(new java.awt.Color(0, 51, 204));
        jLabelRutaRelativa4.setText("jLabel9");

        jLabelRutaRelativa5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelRutaRelativa5.setForeground(new java.awt.Color(0, 51, 204));
        jLabelRutaRelativa5.setText("jLabel9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelRutaRelativa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCarpetaTemporales, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRutaRelativa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRutaRelativa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRutaRelativa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRutaRelativa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jTextFieldCarpetaReportes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCarpetaCopias, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCarpetaPdfs, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxActivarDebug)
                            .addComponent(jCheckBoxPermitirInicioSesionMultiple))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCarpetaTemporales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRutaRelativa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCarpetaPdfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRutaRelativa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCarpetaCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRutaRelativa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCarpetaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelRutaRelativa4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelRutaRelativa5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxPermitirInicioSesionMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxActivarDebug)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete2.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disk_blue.png"))); // NOI18N
        jButtonGrabar.setText("Grabar");
        jButtonGrabar.setToolTipText("Grabar los cambios en la configuración");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGrabar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestaurarUltimaCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarUltimaCopiaActionPerformed
        int siNo = JOptionPane.showConfirmDialog(null, "¿Seguro que desea restaurar la última copia realizada?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("src/iconos/help2.png"));
        if(siNo == 0) {
            CopiaSeguridad copia = new CopiaSeguridad();
            if(copia.restaurarCopia(jLabelFechaUltimaCopia.getText())) {
                JOptionPane.showMessageDialog(null, "Copia de seguridad del " + jLabelFechaUltimaCopia.getText() + " restaurada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrió un error al intentar restaurar la última copia", "Error", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/iconos/delete.png"));
            }
        }
    }//GEN-LAST:event_jButtonRestaurarUltimaCopiaActionPerformed

    private void jButtonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaActionPerformed
        if(!String.valueOf(jPasswordFieldActual.getPassword()).equals("") && !String.valueOf(jPasswordFieldNueva.getPassword()).equals("") && !String.valueOf(jPasswordFieldRepetir.getPassword()).equals("")) {
            if(String.valueOf(jPasswordFieldNueva.getPassword()).equals(String.valueOf(jPasswordFieldRepetir.getPassword()))) {
                Conexion con = new Conexion();
                try {
                    ResultSet rs = con.consultar("SELECT password FROM usuarios WHERE nombre='" + usuario + "'");
                
                    while(rs.next()) {
                        if(rs.getString(1).equals(String.valueOf(jPasswordFieldActual.getPassword()))) {
                            if(con.insertarActualizarEliminar("UPDATE usuarios SET password='" + String.valueOf(jPasswordFieldNueva.getPassword()) + "' WHERE nombre='" + usuario + "'") != 0) {
                                JOptionPane.showMessageDialog(null, "Cambio realizado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
                                limpiarCampos();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "La contraseña actual no es correcta", "Aviso", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/iconos/warning.png"));
                        }
                    }
                } catch(SQLException ex) {
                    if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) log.error("[ConfigurarAplicacion.java (jButtonCambiarContraseñaActionPerformed)] SQLException: " + ex.getMessage());
                }
                con.desconectar();
            } else {
                JOptionPane.showMessageDialog(null, "No coincide la contraseña nueva con la repetición", "Aviso", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/iconos/warning.png"));
            }
        }
    }//GEN-LAST:event_jButtonCambiarContraseñaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed
        if(jCheckBoxCopiaAutomatica.isSelected()) {
            Configuracion.getInstance().setProperty("copiaAutomatica", "si");
        } else {
            Configuracion.getInstance().setProperty("copiaAutomatica", "no");
        }
        Configuracion.getInstance().setProperty("fechaUltimaCopia", jLabelFechaUltimaCopia.getText());
        if(jCheckBoxPermitirInicioSesionMultiple.isSelected()) {
            Configuracion.getInstance().setProperty("inicioSesionMultiple", "si");
        } else {
            Configuracion.getInstance().setProperty("inicioSesionMultiple", "no");
        }
        if(jCheckBoxActivarDebug.isSelected()) {
            Configuracion.getInstance().setProperty("debug", "si");
        } else {
            Configuracion.getInstance().setProperty("debug", "no");
        }
        JOptionPane.showMessageDialog(null, "Cambios guardados con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
        this.dispose();
    }//GEN-LAST:event_jButtonGrabarActionPerformed
    
    public void limpiarCampos() {
        jPasswordFieldActual.setText("");
        jPasswordFieldNueva.setText("");
        jPasswordFieldRepetir.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigurarAplicacion dialog = new ConfigurarAplicacion(new javax.swing.JFrame(), "", true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarContraseña;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JButton jButtonRestaurarUltimaCopia;
    private javax.swing.JCheckBox jCheckBoxActivarDebug;
    private javax.swing.JCheckBox jCheckBoxCopiaAutomatica;
    private javax.swing.JCheckBox jCheckBoxPermitirInicioSesionMultiple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFechaUltimaCopia;
    private javax.swing.JLabel jLabelRutaRelativa1;
    private javax.swing.JLabel jLabelRutaRelativa2;
    private javax.swing.JLabel jLabelRutaRelativa3;
    private javax.swing.JLabel jLabelRutaRelativa4;
    private javax.swing.JLabel jLabelRutaRelativa5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldActual;
    private javax.swing.JPasswordField jPasswordFieldNueva;
    private javax.swing.JPasswordField jPasswordFieldRepetir;
    private javax.swing.JTextField jTextFieldCarpetaCopias;
    private javax.swing.JTextField jTextFieldCarpetaPdfs;
    private javax.swing.JTextField jTextFieldCarpetaReportes;
    private javax.swing.JTextField jTextFieldCarpetaTemporales;
    private javax.swing.JTextField jTextFieldNombreReporte;
    // End of variables declaration//GEN-END:variables
}
