package ventanas;

import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import motor.Clientes;
import motor.Conexion;
import motor.Configuracion;
import motor.Lugares;
import motor.Main;
import motor.Visitas;
import org.apache.log4j.Logger;

/**
 *
 * @author jose
 */
public class NuevoCliente extends javax.swing.JDialog {  
    private int idCliente = 0;
    private int idLugar = 0;
    private Logger log;
    
    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente(java.awt.Frame parent, String titulo, String idCliente, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle(titulo);
        this.setLocationRelativeTo(null);
        
        // Iniciamos el log, si tenemos activo el debug
        if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) {
            Main iniciarlog = new Main();
            log = iniciarlog.getLog();
        }
        
        // Etiqueta para almacenar el id seleccionado del maestro
        jLabelIdLugar.setText("");
        jLabelIdLugar.setVisible(false);
        jButtonEliminar.setVisible(false);
        
        if(!idCliente.equals("")) {
            this.idCliente = Integer.parseInt(idCliente);
            // Desactivamos los campos de "Nombre" y "Descripción"
            jTextFieldNomCliente.setEnabled(false);
            jTextFieldDescLugar.setEnabled(false);
            jButtonEliminar.setVisible(true);
            // Seleccionar los datos del cliente
            obtenerDatosClienteLugar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCPCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPobCliente = new javax.swing.JTextField();
        jTextFieldDirCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldProCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFaxCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOtrosDatos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDescLugar = new javax.swing.JTextField();
        jButtonSelLugar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCPLugar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPobLugar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldProLugar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTelLugar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFaxLugar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEmailLugar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBrickLugar = new javax.swing.JTextField();
        jLabelIdLugar = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldDirLugar = new javax.swing.JTextField();
        jButtonGrabar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Dirección:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cód. Postal:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Población:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Provincia:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fax:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Otros datos:");

        jTextAreaOtrosDatos.setColumns(20);
        jTextAreaOtrosDatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaOtrosDatos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOtrosDatos);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldDirCliente)
                    .add(jTextFieldNomCliente)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFieldCPCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFieldTelCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel7)))
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFieldPobCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextFieldProCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFieldFaxCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextFieldEmailCliente))))
                    .add(jScrollPane1))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldNomCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextFieldDirCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextFieldCPCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jTextFieldPobCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jTextFieldProCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextFieldTelCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(jTextFieldFaxCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jTextFieldEmailCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Lugar Visita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Descripción:");

        jButtonSelLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/view.png"))); // NOI18N
        jButtonSelLugar.setToolTipText("Acceso al maestro");
        jButtonSelLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelLugarActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Cód. Postal:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Población:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Provincia:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Teléfono:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Fax:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Email:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Brick:");

        jLabelIdLugar.setForeground(new java.awt.Color(0, 51, 204));
        jLabelIdLugar.setText("idLugar");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Dirección:");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel16))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jTextFieldCPLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextFieldPobLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextFieldProLugar))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(jTextFieldBrickLugar)
                                    .add(jTextFieldTelLugar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(jLabel14)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jTextFieldFaxLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jTextFieldEmailLugar))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .add(323, 323, 323)
                                        .add(jLabelIdLugar))))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel18)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jTextFieldDescLugar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonSelLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jTextFieldDirLugar))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel9)
                        .add(jTextFieldDescLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonSelLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldDirLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldCPLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(jLabel11)
                    .add(jTextFieldPobLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(jTextFieldProLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldTelLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(jLabel14)
                    .add(jTextFieldFaxLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15)
                    .add(jTextFieldEmailLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldBrickLugar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(jLabelIdLugar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disk_blue.png"))); // NOI18N
        jButtonGrabar.setText("Grabar");
        jButtonGrabar.setToolTipText("Grabar datos de cliente");
        jButtonGrabar.setMaximumSize(new java.awt.Dimension(116, 36));
        jButtonGrabar.setMinimumSize(new java.awt.Dimension(116, 36));
        jButtonGrabar.setPreferredSize(new java.awt.Dimension(116, 36));
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete2.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(116, 36));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(116, 36));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(116, 36));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user1_delete.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setToolTipText("Eliminar cliente");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(jButtonEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButtonCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonGrabar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonGrabar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonEliminar)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed
        // Verificamos que tenemos nombre del cliente y descripción del lugar de visita
        if(jTextFieldNomCliente.getText().isEmpty() == false && jTextFieldDescLugar.getText().isEmpty() == false) {
            Lugares lugar = new Lugares();
            // Verificamos si se ha seleccionado un lugar de visita del maestro
            if(jLabelIdLugar.getText().equals("")) {
                if(idCliente == 0) {
                    idLugar = lugar.grabarLugar("INSERT INTO lugares VALUES(?,'" + jTextFieldDescLugar.getText() + 
                                                    "','" + jTextFieldDirLugar.getText() + "','" + jTextFieldCPLugar.getText() + "','" + jTextFieldPobLugar.getText() + 
                                                    "','" + jTextFieldProLugar.getText() + "','" + jTextFieldTelLugar.getText() + 
                                                    "','" + jTextFieldFaxLugar.getText() + "','" + jTextFieldEmailLugar.getText() + 
                                                    "','" + jTextFieldBrickLugar.getText() + "','','','')");
                } else {
                    lugar.actualizarLugar("UPDATE lugares SET descripcion='" + jTextFieldDescLugar.getText() + "',direccion='" + jTextFieldDirLugar.getText() +
                                            "',cod_postal='" + jTextFieldCPLugar.getText() + "',poblacion='" + jTextFieldPobLugar.getText() + 
                                            "',provincia='" + jTextFieldProLugar.getText() + "',telefono='" + jTextFieldTelLugar.getText() + 
                                            "',fax='" + jTextFieldFaxLugar.getText() + "',email='" + jTextFieldEmailLugar.getText() + 
                                            "',brick='" + jTextFieldBrickLugar.getText() + "' WHERE id=" + idLugar);
                }
            } else {
                idLugar = Integer.parseInt(jLabelIdLugar.getText());
                lugar.actualizarLugar("UPDATE lugares SET descripcion='" + jTextFieldDescLugar.getText() + "',direccion='" + jTextFieldDirLugar.getText() +
                                        "',cod_postal='" + jTextFieldCPLugar.getText() + "',poblacion='" + jTextFieldPobLugar.getText() + 
                                        "',provincia='" + jTextFieldProLugar.getText() + "',telefono='" + jTextFieldTelLugar.getText() + 
                                        "',fax='" + jTextFieldFaxLugar.getText() + "',email='" + jTextFieldEmailLugar.getText() + 
                                        "',brick='" + jTextFieldBrickLugar.getText() + "' WHERE id=" + idLugar);
            }
            if(idLugar != 0) {
                Clientes cliente = new Clientes();
                if(idCliente == 0) {
                    idCliente = cliente.grabarCliente("INSERT INTO clientes VALUES(?,'" + jTextFieldNomCliente.getText() + 
                                                        "','" + jTextFieldDirCliente.getText() + "','" + jTextFieldCPCliente.getText() + 
                                                        "','" + jTextFieldPobCliente.getText() + "','" + jTextFieldProCliente.getText() + 
                                                        "','" + jTextFieldTelCliente.getText() + "','" + jTextFieldFaxCliente.getText() + 
                                                        "','" + jTextFieldEmailCliente.getText() + "','" + jTextAreaOtrosDatos.getText() + "'," + idLugar + ")");
                    
                    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy'-'MM'-'dd", new Locale("es_ES"));
                    Date fecha = new Date();
                    String fechaActualFormateada = formatoFecha.format(fecha);
                    System.out.println(fechaActualFormateada);
                    
                    Visitas visita = new Visitas();
                    if(visita.grabarVisita("INSERT INTO visitas VALUES(?,date('" + fechaActualFormateada + "'),'Alta inicial',1," + idCliente + ")")) { 
                        JOptionPane.showMessageDialog(null, "Cliente grabado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
                    }
                } else {
                    cliente.actualizarCliente("UPDATE clientes SET nombre='" + jTextFieldNomCliente.getText() + 
                                                "',direccion='" + jTextFieldDirCliente.getText() + "',cod_postal='" + jTextFieldCPCliente.getText() + 
                                                "',poblacion='" + jTextFieldPobCliente.getText() + "',provincia='" + jTextFieldProCliente.getText() + 
                                                "',telefono='" + jTextFieldTelCliente.getText() + "',fax='" + jTextFieldFaxCliente.getText() + 
                                                "',email='" + jTextFieldEmailCliente.getText() + "',otros_datos='" + jTextAreaOtrosDatos.getText() + "',id_lugar=" + idLugar + " WHERE id=" + idCliente);
                    JOptionPane.showMessageDialog(null, "Cliente actualizado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Indique un lugar de visita", "Aviso", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/iconos/warning.png")); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene al menos los campos 'Nombre' y 'Descripción'", "Aviso", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/iconos/warning.png")); 
        }
    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSelLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelLugarActionPerformed
        String[] cabecera = new String[2];
        cabecera[0] = "Código";
        cabecera[1] = "Descripción";
        Maestro lugares = new Maestro(NuevoCliente.this,"Maestro de Lugares", "SELECT lugares.id, lugares.descripcion FROM lugares", cabecera, true);
        lugares.setVisible(true);
        
        this.addWindowFocusListener(new WindowFocusListener() {        
            @Override
            public void windowGainedFocus(WindowEvent e) {
                int idLugar = Maestro.getIdSeleccionado();
                seleccionarLugar(idLugar);
            }

            @Override
            public void windowLostFocus(WindowEvent e) {
                // No hacemos nada
            }
        });
    }//GEN-LAST:event_jButtonSelLugarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int siNo = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar los datos de cliente y sus visitas asociadas?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("src/iconos/help2.png"));
        if(siNo == 0) {
            Conexion con = new Conexion();

            if(con.insertarActualizarEliminar("DELETE FROM clientes WHERE clientes.id=" + idCliente) != 0) {
                JOptionPane.showMessageDialog(null, "Cliente y visitas asociadas eliminadas con éxito", "Información", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/iconos/information.png"));
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed
    
    private void seleccionarLugar(int lugar) {
        Conexion con = new Conexion();
        
        try {
            ResultSet rs = con.consultar("SELECT lugares.descripcion, lugares.cod_postal, lugares.poblacion, lugares.provincia, lugares.telefono, lugares.fax, lugares.email, lugares.brick FROM lugares WHERE lugares.id=" + lugar + ";");
                        
            while(rs.next()) {
                jTextFieldDescLugar.setText(rs.getString(1));
                jTextFieldCPLugar.setText(rs.getString(2));
                jTextFieldPobLugar.setText(rs.getString(3));
                jTextFieldProLugar.setText(rs.getString(4));
                jTextFieldTelLugar.setText(rs.getString(5));
                jTextFieldFaxLugar.setText(rs.getString(6));
                jTextFieldEmailLugar.setText(rs.getString(7));
                jTextFieldBrickLugar.setText(rs.getString(8));
                jLabelIdLugar.setText(Integer.toString(lugar));
                
                jTextFieldDescLugar.setEnabled(false);
            }
            rs.close();
        } catch (SQLException ex) {
            if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) log.error("[NuevoCliente.java (seleccionarLugar)] SQLException: " + ex.getMessage());
        }
        con.desconectar();
    }
    
    public void obtenerDatosClienteLugar() {
        Conexion con = new Conexion();
        
        try {
            ResultSet rs = con.consultar("SELECT clientes.*, lugares.* FROM clientes, lugares WHERE clientes.id=" + idCliente + " AND clientes.id_lugar=lugares.id");
            
            while(rs.next()) {
                jTextFieldNomCliente.setText(rs.getString(2));
                jTextFieldDirCliente.setText(rs.getString(3));
                jTextFieldCPCliente.setText(rs.getString(4));
                jTextFieldPobCliente.setText(rs.getString(5));
                jTextFieldProCliente.setText(rs.getString(6));
                jTextFieldTelCliente.setText(rs.getString(7));
                jTextFieldFaxCliente.setText(rs.getString(8));
                jTextFieldEmailCliente.setText(rs.getString(9));
                jTextAreaOtrosDatos.setText(rs.getString(10));
                
                jLabelIdLugar.setText(rs.getString(12));
                idLugar = Integer.parseInt(jLabelIdLugar.getText());
                jTextFieldDescLugar.setText(rs.getString(13));
                jTextFieldDirLugar.setText(rs.getString(14));
                jTextFieldCPLugar.setText(rs.getString(15));
                jTextFieldPobLugar.setText(rs.getString(16));
                jTextFieldProLugar.setText(rs.getString(17));
                jTextFieldTelLugar.setText(rs.getString(18));
                jTextFieldFaxLugar.setText(rs.getString(19));
                jTextFieldEmailLugar.setText(rs.getString(20));
                jTextFieldBrickLugar.setText(rs.getString(21));       
            }
            rs.close();
        } catch(SQLException ex) {
            if(Configuracion.getInstance().getProperty(Configuracion.DEBUG).equals("si")) log.error("[NuevoCliente.java (obtenerDatosClienteLugar)] SQLException: " + ex.getMessage());
        }
        con.desconectar();
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoCliente dialog = new NuevoCliente(new javax.swing.JFrame(), "", "", true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JButton jButtonSelLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdLugar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOtrosDatos;
    private javax.swing.JTextField jTextFieldBrickLugar;
    private javax.swing.JTextField jTextFieldCPCliente;
    private javax.swing.JTextField jTextFieldCPLugar;
    private javax.swing.JTextField jTextFieldDescLugar;
    private javax.swing.JTextField jTextFieldDirCliente;
    private javax.swing.JTextField jTextFieldDirLugar;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldEmailLugar;
    private javax.swing.JTextField jTextFieldFaxCliente;
    private javax.swing.JTextField jTextFieldFaxLugar;
    private javax.swing.JTextField jTextFieldNomCliente;
    private javax.swing.JTextField jTextFieldPobCliente;
    private javax.swing.JTextField jTextFieldPobLugar;
    private javax.swing.JTextField jTextFieldProCliente;
    private javax.swing.JTextField jTextFieldProLugar;
    private javax.swing.JTextField jTextFieldTelCliente;
    private javax.swing.JTextField jTextFieldTelLugar;
    // End of variables declaration//GEN-END:variables
}
